import { execSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, "..");
const buildDir = join(rootDir, "build");
const outWasm = join(buildDir, "optimized.wasm");
const srcWasmDir = join(rootDir, "src", "wasm");
const outJs = join(srcWasmDir, "wasm_bytes.js");

if (!existsSync(buildDir)) {
    mkdirSync(buildDir, { recursive: true });
}
if (!existsSync(srcWasmDir)) {
    mkdirSync(srcWasmDir, { recursive: true });
}

console.log("Compiling AssemblyScript WASM kernels...");
execSync("npx asc src/wasm/entry.as -O3 --enable simd --enable threads -o build/optimized.wasm", {
    cwd: rootDir,
    stdio: "inherit",
});

const wasmBytes = readFileSync(outWasm);
const base64 = wasmBytes.toString("base64");

const fileContent = `// Auto-generated by scripts/build-wasm.js. Do not edit directly.
export const WASM_BASE64 = "${base64}";
`;

writeFileSync(outJs, fileContent, "utf8");
console.log(`Successfully generated ${outJs} (${wasmBytes.length} bytes WASM binary).`);
