export * from "./util/index.js";
export * from "./numerical/index.js";
export * from "./metrics/index.js";
export * from "./matrix/index.js";
export * from "./knn/index.js";
export * from "./datastructure/index.js";
export * from "./linear_algebra/index.js";
export * from "./dimred/index.js";
export * from "./optimization/index.js";
export * from "./clustering/index.js";
//export { version } from "../package.json" assert { type: "json"};
export const version = "0.7.3";
